# Generated by Django 4.2.1 on 2023-06-17 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_merge_20230617_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
